extends: airbnb-base
rules:
  key-spacing:
    - error
    - align: value
  no-multi-spaces:
    - error
    - exceptions:
        VariableDeclarator: true
  no-console: 0
  strict: 0
  func-names: 0
  no-param-reassign: 0
